apiVersion: v1
kind: Service
metadata:
  name: {{ include "bead-website.fullname" . }}
  labels:
{{ include "bead-website.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "bead-website.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
